version: '3.8'

services:
  minidsp-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MINIDSP_API_URL=http://minidsp-rs:5380
    depends_on:
      - minidsp-rs

  minidsp-rs:
    image: mrene/minidsp-rs
    privileged: true  # Needed for USB device access
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - "5380:5380"
    command: ["server", "--http", "0.0.0.0:5380"] 