name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  docker:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Read config
        id: config
        run: |
          REPO=$(jq -r '.docker.repository' config.default.json)
          echo "repository=${REPO}" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push development image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.config.outputs.repository }}/minidsp-ui:dev
            ${{ steps.config.outputs.repository }}/minidsp-ui:dev-${{ github.sha }} 