name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., v1.0.0)'
        required: true
        type: string
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.config.outputs.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Read config
        id: config
        run: |
          REPO=$(jq -r '.docker.repository' config.default.json)
          echo "repository=${REPO}" >> $GITHUB_OUTPUT

  docker:
    needs: prepare
    uses: ./.github/workflows/docker-build.yml
    with:
      tags: |
        ${{ needs.prepare.outputs.repository }}/minidsp-ui:latest
        ${{ needs.prepare.outputs.repository }}/minidsp-ui:${{ inputs.version }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
  release:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true 